# Generated by Django 4.2.4 on 2023-08-31 08:51

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('DADOS', 'Data'), ('TECNOLOGIA', 'Technology'), ('PRODUTO', 'Product')], max_length=20)),
                ('alunos', models.ManyToManyField(related_name='escolas', to='backend.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TAREFAS', 'Tasks'), ('DESAFIOS', 'Challenges'), ('PROJETOS', 'Projects')], max_length=20)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3, validators=[backend.models.validate_interval])),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_do_aluno', to='backend.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_da_escola', to='backend.escola')),
            ],
        ),
    ]
