# Generated by Django 4.2.4 on 2023-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_atividade_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('tasks', 'tarefas'), ('challenges', 'desafios'), ('projects', 'projetos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(choices=[('data', 'dados'), ('technology', 'tecnologia'), ('product', 'produto')], max_length=20, unique=True),
        ),
    ]
